// config.js
export const SUPABASE_URL = "https://nnktuardzsmmckjzrgij.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ua3R1YXJkenNtbWNranpyZ2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NzU4MTYsImV4cCI6MjA3NDI1MTgxNn0.a4yi_syViC9lYuRMx4YmaVOCvFdpPXLVtdAnXJQlpD0";